Repository vestrel00/contacts-android, pull requests merged in 2021-12, with the labels that each got.

#125 Closes #123 Use sealed interfaces!
  core/src/main/java/contacts/core/Fields.kt
  core/src/main/java/contacts/core/OrderBy.kt
  core/src/main/java/contacts/core/Update.kt
  core/src/main/java/contacts/core/data/DataQuery.kt
  core/src/main/java/contacts/core/entities/Contact.kt
  core/src/main/java/contacts/core/entities/CustomData.kt
  core/src/main/java/contacts/core/entities/Data.kt
  core/src/main/java/contacts/core/entities/Entity.kt
  core/src/main/java/contacts/core/entities/Group.kt
  core/src/main/java/contacts/core/entities/MimeType.kt
  core/src/main/java/contacts/core/entities/RawContact.kt
  core/src/main/java/contacts/core/entities/cursor/ContactIdCursor.kt
  core/src/main/java/contacts/core/entities/cursor/DataIdCursor.kt
  core/src/main/java/contacts/core/entities/cursor/JoinedContactsCursor.kt
  core/src/main/java/contacts/core/entities/cursor/RawContactIdCursor.kt
  core/src/main/java/contacts/core/entities/custom/AbstractCustomDataCursor.kt
  core/src/main/java/contacts/core/entities/custom/AbstractCustomDataOperation.kt
  core/src/main/java/contacts/core/entities/custom/AbstractCustomEntityMapper.kt
  core/src/main/java/contacts/core/entities/custom/CustomDataEntityHolder.kt
  core/src/main/java/contacts/core/entities/custom/CustomDataFieldMapper.kt
  core/src/main/java/contacts/core/entities/custom/CustomDataRegistry.kt
  core/src/main/java/contacts/core/entities/mapper/BlankRawContactMapper.kt
  core/src/main/java/contacts/core/entities/table/Table.kt
  core/src/main/java/contacts/core/util/ContactData.kt
  core/src/main/java/contacts/core/util/ContactPhoto.kt
  core/src/main/java/contacts/core/util/RawContactPhoto.kt
  customdata-gender/src/main/java/contacts/entities/custom/gender/Gender.kt
  customdata-handlename/src/main/java/contacts/entities/custom/handlename/HandleName.kt
  sample/src/main/java/contacts/sample/view/ContactView.kt
  test/src/main/java/contacts/test/entities/TestData.kt
  ui/src/main/java/contacts/ui/entities/DataEntityFactory.kt
  ui/src/main/java/contacts/ui/entities/DataEntityTypeFactory.kt
Labels: refactor

#127 Closes #122 Remove explicit dependency on the Kotlin stdlib
  async/build.gradle
  build.gradle
  core/build.gradle
  customdata-gender/build.gradle
  customdata-handlename/build.gradle
  debug/build.gradle
  permissions/build.gradle
  sample/build.gradle
  test/build.gradle
  ui/build.gradle
Labels: build

#149 Closes #148 Refactored Where structure to a binary tree for lazy evaluation
  core/src/main/java/contacts/core/Where.kt
Labels: refactor

#151 Closes #150 Shorten usage of Fields in include, where, and orderBy API functions
  README.md
  async/src/main/java/contacts/async/data/DataQueryAsync.kt
  core/src/main/java/contacts/core/BroadQuery.kt
  core/src/main/java/contacts/core/Insert.kt
  core/src/main/java/contacts/core/Query.kt
  core/src/main/java/contacts/core/Update.kt
  core/src/main/java/contacts/core/Where.kt
  core/src/main/java/contacts/core/accounts/AccountsRawContactsQuery.kt
  core/src/main/java/contacts/core/data/DataQuery.kt
  core/src/main/java/contacts/core/data/DataUpdate.kt
  core/src/main/java/contacts/core/groups/GroupsQuery.kt
  core/src/main/java/contacts/core/profile/ProfileInsert.kt
  core/src/main/java/contacts/core/profile/ProfileQuery.kt
  core/src/main/java/contacts/core/profile/ProfileUpdate.kt
  core/src/main/java/contacts/core/util/ContactLinkResult.kt
  core/src/main/java/contacts/core/util/ContactRefresh.kt
  core/src/main/java/contacts/core/util/FieldsWhere.kt
  core/src/main/java/contacts/core/util/GroupMembershipGroup.kt
  core/src/main/java/contacts/core/util/GroupsInsertResult.kt
  core/src/main/java/contacts/core/util/InsertResult.kt
  core/src/main/java/contacts/core/util/RawContactRefresh.kt
  customdata-gender/src/main/java/contacts/entities/custom/gender/GenderDataQuery.kt
  customdata-gender/src/main/java/contacts/entities/custom/gender/GenderFields.kt
  customdata-handlename/src/main/java/contacts/entities/custom/handlename/HandleNameDataQuery.kt
  customdata-handlename/src/main/java/contacts/entities/custom/handlename/HandleNameFields.kt
  howto/howto-include-only-desired-data.md
  howto/howto-insert-contacts.md
  howto/howto-insert-groups.md
  howto/howto-insert-profile.md
  howto/howto-query-contacts-advanced.md
  howto/howto-query-contacts.md
  howto/howto-query-custom-data.md
  howto/howto-query-data-sets.md
  howto/howto-query-groups.md
  howto/howto-query-profile.md
  howto/howto-query-raw-contacts.md
  howto/howto-update-contacts.md
  howto/howto-update-data-sets.md
  howto/howto-update-profile.md
  sample/src/main/java/contacts/sample/view/ContactView.kt
  test/src/main/java/contacts/test/TestQuery.kt
  test/src/main/java/contacts/test/entities/TestDataFields.kt
Labels: enhancement

#156 Closes #154 Standardize interface for CRUD APIs
  core/src/main/java/contacts/core/BroadQuery.kt
  core/src/main/java/contacts/core/Contacts.kt
  core/src/main/java/contacts/core/CrudApi.kt
  core/src/main/java/contacts/core/Delete.kt
  core/src/main/java/contacts/core/Include.kt
  core/src/main/java/contacts/core/Insert.kt
  core/src/main/java/contacts/core/Query.kt
  core/src/main/java/contacts/core/Update.kt
  core/src/main/java/contacts/core/accounts/Accounts.kt
  core/src/main/java/contacts/core/accounts/AccountsLocalRawContactsUpdate.kt
  core/src/main/java/contacts/core/accounts/AccountsQuery.kt
  core/src/main/java/contacts/core/accounts/AccountsRawContactsQuery.kt
  core/src/main/java/contacts/core/data/Data.kt
  core/src/main/java/contacts/core/data/DataDelete.kt
  core/src/main/java/contacts/core/data/DataQuery.kt
  core/src/main/java/contacts/core/data/DataUpdate.kt
  core/src/main/java/contacts/core/entities/custom/CustomDataRegistry.kt
  core/src/main/java/contacts/core/groups/Groups.kt
  core/src/main/java/contacts/core/groups/GroupsDelete.kt
  core/src/main/java/contacts/core/groups/GroupsInsert.kt
  core/src/main/java/contacts/core/groups/GroupsQuery.kt
  core/src/main/java/contacts/core/groups/GroupsUpdate.kt
  core/src/main/java/contacts/core/profile/Profile.kt
  core/src/main/java/contacts/core/profile/ProfileDelete.kt
  core/src/main/java/contacts/core/profile/ProfileInsert.kt
  core/src/main/java/contacts/core/profile/ProfileQuery.kt
  core/src/main/java/contacts/core/profile/ProfileUpdate.kt
  core/src/main/java/contacts/core/util/ContactLinks.kt
  core/src/main/java/contacts/core/util/ContactOptions.kt
  core/src/main/java/contacts/core/util/ContactPhoto.kt
  core/src/main/java/contacts/core/util/DefaultContactData.kt
  core/src/main/java/contacts/core/util/RawContactOptions.kt
  core/src/main/java/contacts/core/util/RawContactPhoto.kt
  permissions/src/main/java/contacts/permissions/accounts/AccountsPermissionsRequest.kt
  permissions/src/main/java/contacts/permissions/data/DataPermissionsRequest.kt
  permissions/src/main/java/contacts/permissions/groups/GroupsPermissionsRequest.kt
  permissions/src/main/java/contacts/permissions/profile/ProfilePermissionsRequest.kt
  sample/src/main/java/contacts/sample/SampleApp.kt
  test/src/main/java/contacts/test/TestContacts.kt
  test/src/main/java/contacts/test/TestQuery.kt
Labels: refactor
